FROM golang:1.21-alpine

WORKDIR /app

COPY go.mod .

RUN go mod download

COPY . .

# Install air for hot reloading
RUN go install github.com/cosmtrek/air@v1.42.0

EXPOSE 80

CMD ["air", "-c", ".air.toml"]
