FROM node:21

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Generate Prisma client
RUN npx prisma generate

# Create necessary directories for proto files
RUN mkdir -p dist/proto
RUN cp -r src/proto/* dist/proto/

EXPOSE 3002

CMD ["npm", "run", "dev"]
