# Gateway Service Configuration
services:
  # Authentication Service
  authentication:
    url: http://authentication:3001
    prefix: /api/auth
    
  # Authorization Service
  authorization:
    url: http://authorization:3002
    prefix: /api/authorize
    
  # User Service
  user:
    url: http://user:3003
    prefix: /api/users
